---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines 

params:
  pcf_ert_domain:

run:
  path: pcf-pipelines/install-pcf/gcp/tasks/check-opsman-dns/task.sh
