---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 
  - name: terraform-state
params:
  PEM:
  ERT_DOMAIN:
  DB_APP_USAGE_SERVICE_USERNAME:
  DB_APP_USAGE_SERVICE_PASSWORD:
  DB_AUTOSCALE_USERNAME:
  DB_AUTOSCALE_PASSWORD:
  DB_DIEGO_USERNAME:
  DB_DIEGO_PASSWORD:
  DB_NOTIFICATIONS_USERNAME:
  DB_NOTIFICATIONS_PASSWORD:
  DB_ROUTING_USERNAME:
  DB_ROUTING_PASSWORD:
  DB_UAA_USERNAME:
  DB_UAA_PASSWORD:
  DB_CCDB_USERNAME:
  DB_CCDB_PASSWORD:
  DB_ACCOUNTDB_USERNAME:
  DB_ACCOUNTDB_PASSWORD:
  DB_NETWORKPOLICYSERVERDB_USERNAME:
  DB_NETWORKPOLICYSERVERDB_PASSWORD:
  DB_NFSVOLUMEDB_USERNAME:
  DB_NFSVOLUMEDB_PASSWORD:
run:
  path: pcf-pipelines/install-pcf/aws/tasks/prepare-rds/task.sh
