---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 
  - name: terraform-state
outputs:
  - name: terraform-state-output
params:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  TF_VAR_aws_access_key:
  TF_VAR_aws_secret_key:
  TF_VAR_aws_key_name:
  TF_VAR_aws_cert_arn:
  TF_VAR_amis_nat:
  TF_VAR_aws_region:
  TF_VAR_az1:
  TF_VAR_az2:
  TF_VAR_az3:
  TF_VAR_route53_zone_id:
  TF_VAR_vpc_cidr:
  TF_VAR_public_subnet_cidr_az1:
  TF_VAR_public_subnet_cidr_az2:
  TF_VAR_public_subnet_cidr_az3:
  TF_VAR_ert_subnet_cidr_az1:
  TF_VAR_ert_subnet_cidr_az2:
  TF_VAR_ert_subnet_cidr_az3:
  TF_VAR_services_subnet_cidr_az1:
  TF_VAR_services_subnet_cidr_az2:
  TF_VAR_services_subnet_cidr_az3:
  TF_VAR_infra_subnet_cidr_az1:
  TF_VAR_rds_subnet_cidr_az1:
  TF_VAR_rds_subnet_cidr_az2:
  TF_VAR_rds_subnet_cidr_az3:
  OPSMAN_ALLOW_SSH_CIDR_RANGES:
  OPSMAN_ALLOW_HTTPS_CIDR_RANGES:
run:
  path: pcf-pipelines/install-pcf/aws/tasks/wipe-env/task.sh
