---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 
params:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
run:
  path: pcf-pipelines/install-pcf/vsphere/tasks/wipe-env/task.sh
